FROM zurajm/alpine-python3:3.7.5-arm
MAINTAINER Miha Zuraj

# Uncomment next line if building in x86 host
COPY qemu-arm-static /usr/bin/

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

RUN pip install --no-cache-dir gitpython pyotp

WORKDIR /app
COPY ./src/configurator.py ./run.sh /app/
RUN chmod a+x ./configurator.py ./run.sh

# Default listening port.
EXPOSE 3218

# The configuration yaml for persistance.
VOLUME /config

ENTRYPOINT ["/app/run.sh"]
